# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0ec155a6a11396c7f7b4038571077aa574ab62671aca06e7416f0721051c1643fedecfd799151ddb2a0bbc259fb4dc7b581e2a20da84d289b4aef97fdb4734

test:
  secret_key_base: 19d8434f58f5dceaf6837004d9e904da72abc49961ddbae127f8374c3e117db15dccf487c366c526ac787a374e3de9abe9682b62191419d8c18a284fcc41bafa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
